import type { Metadata } from "next";

import "../styles/index.scss"

export const metadata: Metadata = {
  title: "Learn ABC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ms">
      <body>
        <div className="row justify-content-center mt-5">
          <div className="col-4 text-center mt-5">
            <div className="card card-custom">
              <div className="card-body">
                <h1 className="card-title">Let's learn A B C!</h1>
              </div>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
