import type { Metadata } from "next";

import "../styles/index.scss"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ms">
      <body>
        <div className="row mt-5">
          <div className="col-12 text-center mt-5">
            <h1>Let's learn A B C!</h1>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
